# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def load_history(self):
        import sys
        import os

        path = os.path.dirname(os.path.abspath(sys.argv[0]))
        file = open(f"{path}/command_history", "r")
        data = file.readlines()
        file.close()
        for i in data:
            self.listWidget.addItem(i.replace("\n",""))
    def copy_clip_board(self):
        current=self.listWidget.currentItem().text()
        cb = QtGui.QGuiApplication.clipboard()
        cb.setText(current)
        self.status.setText(f"Command Copied: {current}")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 706)
        MainWindow.setStyleSheet("font: 16pt \"Ubuntu Mono\";\n"
"color: rgb(229, 165, 10);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setStyleSheet("font: 13pt \"Ubuntu Mono\";\n"
"color: rgb(198, 70, 0);\n"
"\n"
"\n"
"\n"
"\n"
"border: 0px solid rgb(0, 0, 0)\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setMinimumSize(QtCore.QSize(0, 38))
        self.status.setStyleSheet("font: 13pt \"Ubuntu Mono\";\n"
"color: rgb(229, 165, 10);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.status.setText("")
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.listWidget.setSpacing(5)
        self.load_history()
        self.listWidget.doubleClicked.connect(lambda : self.copy_clip_board())
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Command History"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">Command History:</span></p></body></html>"))
def main():
 import sys
 app = QtWidgets.QApplication(sys.argv)
 w = QtWidgets.QMainWindow()
 ui = Ui_MainWindow()
 ui.setupUi(w)
 w.show()
 sys.exit(app.exec_())
main()