# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dev.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1200, 702)
        MainWindow.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"background-color: rgb(14, 14, 14);\n"
"color: rgb(198, 70, 0);\n"
"font: 11pt \"Ubuntu\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(600, 16777215))
        self.widget.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"background-color: rgb(14, 14, 14);\n"
"color: rgb(198, 70, 0);\n"
"font: 11pt \"Ubuntu\";\n"
"border: 1px solid rgb(165, 29, 45)")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(0, 66))
        self.label.setStyleSheet("border: 1px solid rgb(0,0,0)")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.code_book_path = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.code_book_path.sizePolicy().hasHeightForWidth())
        self.code_book_path.setSizePolicy(sizePolicy)
        self.code_book_path.setMinimumSize(QtCore.QSize(348, 37))
        self.code_book_path.setStyleSheet("\n"
"font: 12pt \"Ubuntu Mono\";\n"
"color: rgb(222, 221, 218);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.code_book_path.setAlignment(QtCore.Qt.AlignCenter)
        self.code_book_path.setObjectName("code_book_path")
        self.horizontalLayout_3.addWidget(self.code_book_path)
        spacerItem1 = QtWidgets.QSpacerItem(23, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.code_dir_add = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.code_dir_add.sizePolicy().hasHeightForWidth())
        self.code_dir_add.setSizePolicy(sizePolicy)
        self.code_dir_add.setMaximumSize(QtCore.QSize(100, 16777215))
        self.code_dir_add.setStyleSheet("border: 1px solid rgb(165, 29, 45)")
        self.code_dir_add.setFlat(True)
        self.code_dir_add.setObjectName("code_dir_add")
        self.horizontalLayout_3.addWidget(self.code_dir_add)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.codebook_dir_combo = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.codebook_dir_combo.sizePolicy().hasHeightForWidth())
        self.codebook_dir_combo.setSizePolicy(sizePolicy)
        self.codebook_dir_combo.setMinimumSize(QtCore.QSize(0, 38))
        self.codebook_dir_combo.setStyleSheet("font: 12pt \"Ubuntu Mono\";\n"
"color: rgb(46, 194, 126);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)")
        self.codebook_dir_combo.setEditable(False)
        self.codebook_dir_combo.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.codebook_dir_combo.setObjectName("codebook_dir_combo")
        self.horizontalLayout_2.addWidget(self.codebook_dir_combo)
        spacerItem2 = QtWidgets.QSpacerItem(11, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.remove_code_dir = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_code_dir.sizePolicy().hasHeightForWidth())
        self.remove_code_dir.setSizePolicy(sizePolicy)
        self.remove_code_dir.setMaximumSize(QtCore.QSize(100, 16777215))
        self.remove_code_dir.setStyleSheet("border: 1px solid rgb(165, 29, 45)")
        self.remove_code_dir.setFlat(True)
        self.remove_code_dir.setObjectName("remove_code_dir")
        self.horizontalLayout_2.addWidget(self.remove_code_dir)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.search_group = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_group.sizePolicy().hasHeightForWidth())
        self.search_group.setSizePolicy(sizePolicy)
        self.search_group.setMinimumSize(QtCore.QSize(281, 44))
        self.search_group.setStyleSheet("\n"
"font: 12pt \"Ubuntu Mono\";\n"
"color: rgb(222, 221, 218);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.search_group.setAlignment(QtCore.Qt.AlignCenter)
        self.search_group.setObjectName("search_group")
        self.verticalLayout_2.addWidget(self.search_group)
        self.group_combo = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_combo.sizePolicy().hasHeightForWidth())
        self.group_combo.setSizePolicy(sizePolicy)
        self.group_combo.setMinimumSize(QtCore.QSize(0, 38))
        self.group_combo.setStyleSheet("font: 12pt \"Ubuntu Mono\";\n"
"color: rgb(46, 194, 126);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)")
        self.group_combo.setEditable(False)
        self.group_combo.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.group_combo.setObjectName("group_combo")
        self.verticalLayout_2.addWidget(self.group_combo)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_codebook = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_codebook.sizePolicy().hasHeightForWidth())
        self.search_codebook.setSizePolicy(sizePolicy)
        self.search_codebook.setMinimumSize(QtCore.QSize(281, 44))
        self.search_codebook.setStyleSheet("\n"
"font: 12pt \"Ubuntu Mono\";\n"
"color: rgb(222, 221, 218);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.search_codebook.setAlignment(QtCore.Qt.AlignCenter)
        self.search_codebook.setObjectName("search_codebook")
        self.verticalLayout.addWidget(self.search_codebook)
        self.codebook_combo = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.codebook_combo.sizePolicy().hasHeightForWidth())
        self.codebook_combo.setSizePolicy(sizePolicy)
        self.codebook_combo.setMinimumSize(QtCore.QSize(0, 38))
        self.codebook_combo.setStyleSheet("font: 12pt \"Ubuntu Mono\";\n"
"color: rgb(46, 194, 126);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)")
        self.codebook_combo.setEditable(False)
        self.codebook_combo.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.codebook_combo.setObjectName("codebook_combo")
        self.verticalLayout.addWidget(self.codebook_combo)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(23, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.root = QtWidgets.QRadioButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.root.sizePolicy().hasHeightForWidth())
        self.root.setSizePolicy(sizePolicy)
        self.root.setMaximumSize(QtCore.QSize(111, 16777215))
        self.root.setStyleSheet("background-color: rgb(0, 0, 0,0);\n"
"border: 1px solid rgb(0,0,0)")
        self.root.setObjectName("root")
        self.horizontalLayout_7.addWidget(self.root)
        self.execute = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.execute.sizePolicy().hasHeightForWidth())
        self.execute.setSizePolicy(sizePolicy)
        self.execute.setMinimumSize(QtCore.QSize(0, 39))
        self.execute.setStyleSheet("border: 1px solid rgb(165, 29, 45)")
        self.execute.setFlat(True)
        self.execute.setObjectName("execute")
        self.horizontalLayout_7.addWidget(self.execute)
        spacerItem4 = QtWidgets.QSpacerItem(23, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.non_root = QtWidgets.QRadioButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.non_root.sizePolicy().hasHeightForWidth())
        self.non_root.setSizePolicy(sizePolicy)
        self.non_root.setMinimumSize(QtCore.QSize(0, 0))
        self.non_root.setMaximumSize(QtCore.QSize(111, 16777215))
        self.non_root.setStyleSheet("background-color: rgb(0, 0, 0,0);\n"
"border: 1px solid rgb(0,0,0)")
        self.non_root.setObjectName("non_root")
        self.horizontalLayout_7.addWidget(self.non_root)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.command_history = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.command_history.sizePolicy().hasHeightForWidth())
        self.command_history.setSizePolicy(sizePolicy)
        self.command_history.setMaximumSize(QtCore.QSize(150, 16777215))
        self.command_history.setStyleSheet("border: 1px solid rgb(165, 29, 45)")
        self.command_history.setFlat(True)
        self.command_history.setObjectName("command_history")
        self.horizontalLayout_5.addWidget(self.command_history)
        self.command = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.command.sizePolicy().hasHeightForWidth())
        self.command.setSizePolicy(sizePolicy)
        self.command.setMinimumSize(QtCore.QSize(348, 37))
        self.command.setStyleSheet("font: 12pt \"Ubuntu Mono\";\n"
"color: rgb(53, 132, 228);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.command.setAlignment(QtCore.Qt.AlignCenter)
        self.command.setObjectName("command")
        self.horizontalLayout_5.addWidget(self.command)
        spacerItem5 = QtWidgets.QSpacerItem(23, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.command_run = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.command_run.sizePolicy().hasHeightForWidth())
        self.command_run.setSizePolicy(sizePolicy)
        self.command_run.setMaximumSize(QtCore.QSize(150, 16777215))
        self.command_run.setStyleSheet("border: 1px solid rgb(165, 29, 45)")
        self.command_run.setFlat(True)
        self.command_run.setObjectName("command_run")
        self.horizontalLayout_5.addWidget(self.command_run)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.group_text = QtWidgets.QTextEdit(self.widget)
        self.group_text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.group_text.setStyleSheet("font: 16pt \"Ubuntu\";\n"
"color: rgb(192, 191, 188);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"")
        self.group_text.setObjectName("group_text")
        self.horizontalLayout_9.addWidget(self.group_text)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.group_name = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_name.sizePolicy().hasHeightForWidth())
        self.group_name.setSizePolicy(sizePolicy)
        self.group_name.setMinimumSize(QtCore.QSize(301, 38))
        self.group_name.setStyleSheet("\n"
"font: 12pt \"Ubuntu Mono\";\n"
"color: rgb(222, 221, 218);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.group_name.setAlignment(QtCore.Qt.AlignCenter)
        self.group_name.setObjectName("group_name")
        self.horizontalLayout_8.addWidget(self.group_name)
        self.add_update_group = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_update_group.sizePolicy().hasHeightForWidth())
        self.add_update_group.setSizePolicy(sizePolicy)
        self.add_update_group.setMinimumSize(QtCore.QSize(0, 38))
        self.add_update_group.setMaximumSize(QtCore.QSize(200, 16777215))
        self.add_update_group.setStyleSheet("border: 1px solid rgb(165, 29, 45)")
        self.add_update_group.setFlat(True)
        self.add_update_group.setObjectName("add_update_group")
        self.horizontalLayout_8.addWidget(self.add_update_group)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.edit_code = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_code.sizePolicy().hasHeightForWidth())
        self.edit_code.setSizePolicy(sizePolicy)
        self.edit_code.setMinimumSize(QtCore.QSize(0, 38))
        self.edit_code.setStyleSheet("border: 1px solid rgb(165, 29, 45)")
        self.edit_code.setFlat(True)
        self.edit_code.setObjectName("edit_code")
        self.horizontalLayout_11.addWidget(self.edit_code)
        self.delete_group = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_group.sizePolicy().hasHeightForWidth())
        self.delete_group.setSizePolicy(sizePolicy)
        self.delete_group.setStyleSheet("border: 1px solid rgb(165, 29, 45)")
        self.delete_group.setFlat(True)
        self.delete_group.setObjectName("delete_group")
        self.horizontalLayout_11.addWidget(self.delete_group)
        self.clear_history = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_history.sizePolicy().hasHeightForWidth())
        self.clear_history.setSizePolicy(sizePolicy)
        self.clear_history.setStyleSheet("border: 1px solid rgb(165, 29, 45)")
        self.clear_history.setFlat(True)
        self.clear_history.setObjectName("clear_history")
        self.horizontalLayout_11.addWidget(self.clear_history)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.status = QtWidgets.QLabel(self.widget)
        self.status.setMinimumSize(QtCore.QSize(0, 38))
        self.status.setStyleSheet("font: 13pt \"Ubuntu Mono\";\n"
"color: rgb(229, 165, 10);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.status.setText("")
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName("status")
        self.verticalLayout_3.addWidget(self.status)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_2.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"background-color: rgb(14, 14, 14);\n"
"color: rgb(198, 70, 0);\n"
"font: 11pt \"Ubuntu\";\n"
"border: 1px solid rgb(165, 29, 45)")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.disp = QtWidgets.QTextBrowser(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disp.sizePolicy().hasHeightForWidth())
        self.disp.setSizePolicy(sizePolicy)
        self.disp.setStyleSheet("font: 25 11pt \"Umpush\";\n"
"color: rgb(46, 204, 113);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"")
        self.disp.setObjectName("disp")
        self.horizontalLayout_12.addWidget(self.disp)
        self.horizontalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        import function
        self.non_root.setChecked(True)
        self.process_group_delete = QtCore.QProcess()
        self.process_dir_delete = QtCore.QProcess()
        self.process_history_delete = QtCore.QProcess()

        function.group_add(self)
        function.codedir_combo_add(self)

        self.add_update_group.clicked.connect(lambda: function.add_group(self))
        self.group_combo.currentIndexChanged.connect(lambda: function.group_show(self))
        self.search_group.textChanged.connect(lambda: function.group_search(self))
        self.code_dir_add.clicked.connect(lambda : function.code_path_add(self))
        self.codebook_dir_combo.currentIndexChanged.connect(lambda : function.codebooks_add(self))
        self.edit_code.clicked.connect(lambda : function.edit_code(self))
        self.process_group_delete.finished.connect(lambda : function.group_add(self))
        self.delete_group.clicked.connect(lambda : function.delete_group(self))
        self.remove_code_dir.clicked.connect(lambda : function.delete_code_dir(self))
        self.process_dir_delete.finished.connect(lambda : function.codedir_combo_add(self))
        self.execute.clicked.connect(lambda : function.execute(self))
        self.command_run.clicked.connect(lambda : function.add_hoc_command_runner(self))
        self.command_history.clicked.connect(lambda : function.command_hist(self))
        self.process_history_delete.finished.connect(lambda : self.status.setText("Command history cleaned!"))
        self.clear_history.clicked.connect(lambda : function.clear_command_hist(self))
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tele-Coder"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">&lt;_-\\~Tele - Coder~/-_&gt;</span></p><p align=\"center\">[Developed by Sourish Datta]</p></body></html>"))
        self.code_book_path.setPlaceholderText(_translate("MainWindow", "Paste codebook dir absolute path"))
        self.code_dir_add.setText(_translate("MainWindow", "Add"))
        self.remove_code_dir.setText(_translate("MainWindow", "Remove"))
        self.search_group.setPlaceholderText(_translate("MainWindow", "Search Server Groups"))
        self.search_codebook.setPlaceholderText(_translate("MainWindow", "Search codebook"))
        self.root.setText(_translate("MainWindow", "Root"))
        self.execute.setText(_translate("MainWindow", "Execute Codebook"))
        self.non_root.setText(_translate("MainWindow", "Non-Root"))
        self.command_history.setText(_translate("MainWindow", "History"))
        self.command.setPlaceholderText(_translate("MainWindow", "ad-hoc command"))
        self.command_run.setText(_translate("MainWindow", "Run"))
        self.group_name.setPlaceholderText(_translate("MainWindow", "New Server Group Name"))
        self.add_update_group.setText(_translate("MainWindow", "Add/Update Server Group"))
        self.edit_code.setText(_translate("MainWindow", "Edit Code"))
        self.delete_group.setText(_translate("MainWindow", "Delete Group"))
        self.clear_history.setText(_translate("MainWindow", "Clear History"))
        self.disp.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Umpush\'; font-size:11pt; font-weight:24; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
def main():
 import sys
 app = QtWidgets.QApplication(sys.argv)
 w = QtWidgets.QMainWindow()
 ui = Ui_MainWindow()
 ui.setupUi(w)
 w.show()
 sys.exit(app.exec_())
main()